image:
  repository: ghcr.io/titouan-gautier/kube-gitops-test
  tag: "fdf298e76f6c44b918ea9c8c1673419a7ffdd584"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

config:
  appVersion: "1.0.0"
  logLevel: "info"

ingress:
  enabled: false
  hostname: "mon-app.local"

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 70

# L'annotation clé pour Prometheus
prometheus:
  scrape: true
  port: 3000
  path: /metrics